## Challenge 9
Advent of Code 2020

Part two of this challenge is the first challenge I failed.
I would like to blame not having enough time for the challenge (not to say I had), but at the end of the day I incredibly confused by the challenge and I don't think I would've been able to do it by myself anyway.

Note that the second part of the challenge is not my code. (Don't know the source)




#### To run this challenge

```sh
python3 One.py #part one
python3 Two.py #part two
```